runtime: go111

handlers:
- url: /tasks/.*
  script: auto

- url: /(.*)
  static_files: frontend/dist/\1
  upload: frontend/dist/(.*)

- url: /
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html
