runtime: go111

handlers:
- url: /tasks/.*
  script: auto

- url: /
  static_files: frontend/index.html
  upload: frontend/index.html

- url: /(.*)
  static_files: frontend/\1
  upload: frontend/(.*)
