runtime: go111

handlers:
- url: /tasks/.*
  script: auto

- url: /static/(.*)
  static_files: frontend/dist/static/\1
  upload: frontend/dist/static/(.*)

- url: /.*
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html
