name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: yarn install, build, and test
      run: |
        cd frontend/
        yarn install
        yarn run build
      env:
        CI: true
    - name: go get
      run: go get -v -t -d ./...
    - name: go test
      run: go test -v ./...
    - name: deploy to gcp app engine
      uses: exelban/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy --quiet app.yaml
