name: CI

on:
  push:
    branches:
      - master

jobs:
  test-js:
    name: Test JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install, build, and test
      run: |
        cd frontend/
        yarn install
        yarn run build
      env:
        CI: true

  test-go:
    name: Test GO
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: go get
      run: go get -v -t -d ./...
    - name: go test
      run: go test -v ./...
