name: CI

on:
  push:
    branches:
      - master

jobs:
  build-js:
    name: Build js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install, build, and test
      run: |
        cd frontend/
        yarn install
        yarn run build
      env:
        CI: true

  test-go:
    name: Test go
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Test
      run: go test -v ./...

  deploy:
    name: Deploy
    needs: [build-js, test-go]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: exelban/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy --quiet app.yaml
